version: '3.8'
services:
  api:
    build: ./apps/api
    env_file: .env
    ports:
      - '3000:3000'
  web:
    build: ./apps/web
    env_file: .env
    ports:
      - '80:3000'
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
volumes:
  db_data:
